nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Host', 'Referer', 'User-Agent', 'Client-Address', 'if-modified-since']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
